# permissions for end users to view ingressresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingressresource-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingress-resource-controller
    app.kubernetes.io/part-of: ingress-resource-controller
    app.kubernetes.io/managed-by: kustomize
  name: ingressresource-viewer-role
rules:
- apiGroups:
  - networking.sp-yduck.com
  resources:
  - ingressresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.sp-yduck.com
  resources:
  - ingressresources/status
  verbs:
  - get
