---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.sp-yduck.com
  resources:
  - ingressresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.sp-yduck.com
  resources:
  - ingressresources/finalizers
  verbs:
  - update
- apiGroups:
  - networking.sp-yduck.com
  resources:
  - ingressresources/status
  verbs:
  - get
  - patch
  - update
